### ISSUE TITLE
Apparent null ref on setup

### ISSUE THREAD

**Issue by jduv** [Racailloux/home-assistant-pijuice#23]
Logs below. I'm not a python guy (I hate significant whitespace), but I assume that `self._attr_native_value` is null, which means it's not being set somehow.

HA version 2024.2.2

I2C is confirmed to be enabled.

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:533
Integration: Sensor (documentation, issues)
First occurred: 10:01:30 AM (1 occurrences)
Last logged: 10:01:30 AM

Error adding entities for domain sensor with platform pijuice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    shadowed_attr[ATTR_ICON] = self.icon
                               ^^^^^^^^^
  File "/config/custom_components/pijuice/sensor.py", line 195, in icon
    if self._attr_native_value > 90:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

Also getting this:

```
This error originated from a custom integration.

Logger: custom_components.pijuice.sensor
Source: custom_components/pijuice/sensor.py:244
Integration: pijuice (documentation, issues)
First occurred: 10:01:22 AM (9 occurrences)
Last logged: 10:01:30 AM

PiJuice: Error while retrieving data for sensor 'Temperature' (Error code: '[Errno 110] Operation timed out')
PiJuice: Error while retrieving data for sensor 'Battery voltage' (Error code: '[Errno 110] Operation timed out')
PiJuice: Error while retrieving data for sensor 'Battery current' (Error code: '[Errno 110] Operation timed out')
PiJuice: Error while retrieving data for sensor 'IO voltage' (Error code: '[Errno 110] Operation timed out')
PiJuice: Error while retrieving data for sensor 'IO current' (Error code: '[Errno 110] Operation timed out')
```

**Comment by jduv** [comment]
Also getting this:

```2024-02-24 10:01:27.076 WARNING (MainThread) [custom_components.pijuice.sensor] PiJuice: Error while retrieving data for sensor 'Battery voltage' (Error code: '[Errno 110] Operation timed out')```
