### ISSUE TITLE
Since  HA core-2021.8.0 plugin does not work anymore

### ISSUE THREAD

**Issue by domowarrior** [Racailloux/home-assistant-pijuice#5]
Hi  Racailloux,

I run HA core on a Raspberry Pi 4

Your plugin worked beautiful until i upgraded to HA Core Version core-2021.8.0  .
All the entities are "' not available".
I rebooted the Pi  , did not help either.

The error log is 
`This error originated from a custom integration.

Logger: homeassistant.config
Source: custom_components/pijuice/sensor.py:12
Integration: pijuice (documentation, issues)
First occurred: 19:00:01 (1 occurrences)
Last logged: 19:00:01

Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 857, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/pijuice/sensor.py", line 12, in <module>
    from homeassistant.const import (
ImportError: cannot import name 'VOLT' from 'homeassistant.const' `(/usr/src/homeassistant/homeassistant/const.py)`

I upgraded to HA Core Version core-2021.8.0 today  and that did not fix it

Could you have a look ?

Regards

Karel

**Comment by Racailloux** [comment]
Hello,

I have the same configuration and got the same issue. that is a global issue on quite several HA addons.
The 2021.8.0 introduced a major re-naming of units.
I will have  look at it and keep you warned of any update.
